services:
    website:
        image: 
            ab6d4e01e10d
        ports:
            - "8081:443"
        volumes:
            - "./website:/var/www/website:ro"
            - "/docker/hannahsite/ssl/domain.key:/etc/ssl/private.key"
        restart: unless-stopped
